services:
  backend:
    build: ./api/
    environment:
      - SE_API_KEY=
      - SE_SITE=
    restart: unless-stopped

  frontend:
    image: sha256:faffa38607ab54581f3287653e8a8404d39ac803fac27b225cb222b623cd7925
    links:
      - backend
    environment:
      - REACT_APP_API_HOST=backend
    ports:
      - 3000:3000
    restart: unless-stopped
