services:
  backend:
    build: ./api/
    hostname: api.yourdomain.com
    ports:
      - 8080:8080
    environment:
      - SE_API_KEY=
      - SE_SITE=
    restart: unless-stopped

  frontend:
    build: .
    environment:
      - SE_API_HOST=api.yourdomain.com
      - SE_API_HTTPS=true
    ports:
      - 3000:3000
    restart: unless-stopped
