name: Publish Docker image

on:
  release:
    types: [published]

jobs:
  push-api:
    name: Build and push API
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@7ca345011ac4304463197fac0e56eab1bc7e6af0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@44d81d6d2a5a935e1a481942268529623f1f5ccd
        with:
          images: jordz0005/solaredge-api

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@7e094594beda23fc8f21fa31049f4b203e51096b
        with:
          context: ./api/
          file: ./api/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  push-web:
    name: Build and push web
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@7ca345011ac4304463197fac0e56eab1bc7e6af0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@44d81d6d2a5a935e1a481942268529623f1f5ccd
        with:
          images: jordz0005/solaredge-web

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@7e094594beda23fc8f21fa31049f4b203e51096b
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
